project_id = "swsmmdnaivarrbjjakmx"

[functions.kpi-export]
verify_jwt = false

[functions.manage-api-key]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-delete-data]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.login-with-identifier]
verify_jwt = false
